# Generated by Django 4.2.2 on 2023-06-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='average_temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
